### ISSUE TITLE
Need help to build the project on raspberry pi 5 (raspberry pi OS)

### ISSUE THREAD

**Issue by rahul8819** [maddinkunze/handcode#1]
I've installed svg2gcode, but I'm unsure how to proceed with balance steps, and I've been unable to locate the convert.py file.

**Comment by maddinkunze** [comment]
Hi sorry for not updating the readme, but you should be able to run `python3 main.py` without needing any external binary dependencies.
Please post any errors that occur as i have not tested HandCode on Linux systems yet

**Comment by rahul8819** [comment]
Thank you for your prompt response. I've encountered an error while running `main.py` on Raspberry Pi OS.

traceback (most recent call last):
  File "/home/pi/hancode/handcode-main/src/main.py", line 709, in <module>
    main()
  File "/home/pi/hancode/handcode-main/src/main.py", line 54, in main
    window.iconbitmap(os.path.join(path_lib, "icon.ico"))
  File "/usr/lib/python3.11/tkinter/_init_.py", line 2136, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: bitmap "/home/pi/hancode/handcode-main/src/lib/icon.ico" not defined

**Comment by maddinkunze** [comment]
Could you try commenting out the line throwing the error (line 54 of main.py)?
This seems to be a common issue in tkinter: https://stackoverflow.com/questions/11176638/tkinter-tclerror-error-reading-bitmap-file

**Comment by rahul8819** [comment]
After commenting out the 54th line, the graphical interface has opened, but another error message has appeared.


The following unhandled

exception occured: No module named 'tensorflow'

Traceback (most recent call

last):

File

"/home/pi/handcode/src/main.py

", line 396, in threadConvert

import handwriting

File

"/home/pi/handcode/src/lib/hand writing/init_.py", line 1, in

<module>

from. import gcode

File

"/home/pi/handcode/src/lib/hand writing/gcode.py", line 3, in <module>

from.rnn import rnn

File

"/home/pi/handcode/src/lib/hand writing/rnn.py", line 5, in

<module>

import tensorflow as tf ModuleNotFoundError: No module named 'tensorflow'

(<class 'ModuleNotFoundError'>, ModuleNotFoundError("No module named 'tensorflow"), <traceback object at 0x7fff888a9e80>)

![handcode](https://github.com/maddinkunze/handcode/assets/107311046/de824151-3c13-4869-9aa0-03a74c11677b)

**Comment by rahul8819** [comment]
After installing TensorFlow using pip, I encountered another error message.
The following unhandled exception occured: main thread is not in main loop

Traceback (most recent call last):

File

"/home/pi/handcode/src/main.py ", line 395, in threadConvert report("log", "Loading tensorflow... ")

File

"/home/pi/han/code/src/main.py ", line 416, in report edtLog.append(data)

File

"/home/pi/handcode/src/lib/tkwi dgets/Scrolled Entry.py", line 20, in append

self.entry.insert(tk.END, text)

File

"/usr/lib/python3.11/tkinter/_ini t_.py", line 3809, in insert self.tk.call((self._w, 'insert', index, chars) + args) RuntimeError: main thread is not in main loop

(<class 'RuntimeError'>, RuntimeError('main thread is not in main loop'), <traceback object at 0x7ffef03c9a00>)


![WhatsApp Image 2024-03-21 at 06 21 11](https://github.com/maddinkunze/handcode/assets/107311046/9a20f200-1de3-4df5-bbdd-c853fa8e7851)

**Comment by maddinkunze** [comment]
Alright, thanks for the logs, i will have a look at this and come back to you in a few hours or so

**Comment by maddinkunze** [comment]
Hi, i think the issues should be resolved, please test again by pulling the latest commit (d52edf9d93ab3a272ae0163d58e34edd48619dae).
Please make sure you have a compatible tensorflow version (2.11.0) installed. You should  be able to install all required tensorflow packages using `pip3 install -r requirements.txt`

**Comment by rahul8819** [comment]
Hi, I think tensorflow version 2.11.0 is not available for Raspberry pi OS, because i got an error like  :

ERROR: Could not find a version that satisfies the requirement tensorflow==2.11.0 (from versions: 2.12.0rc0, 2.12.0rc1, 2.12.0, 2.12.1, 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.13.1, 2.14.0rc0, 2.14.0rc1, 2.14.0, 2.14.1, 2.15.0rc0, 2.15.0rc1, 2.15.0, 2.15.1, 2.16.0rc0, 2.16.1)
ERROR: No matching distribution found for tensorflow==2.11.0

**Comment by maddinkunze** [comment]
You may need an older version of python. I tested on python 3.10.4, you should be able to install it on Raspbian using `sudo apt-get install python3=3.10.4`
Tensorflow 2.11 is sadly not supported on newer versions of python and my code breaks on newer versions of tf. I will try to fix this in the future but this should be a fix for now.

**Comment by rahul8819** [comment]
Yes, I will certainly give that a try. Does the same process apply for Ubuntu as well?

**Comment by maddinkunze** [comment]
Yes, the same process applies to Ubuntu. Other linux distros may use different package managers, so you may need to look up the specific commands (i.e. `yum`, `pacman`, ...) to install the specific python version, but for Debian, Raspbian and Ubuntu `apt` should work.

**Comment by rahul8819** [comment]
On changing pyenv to 3.10.4, Tensorflow and tensorflow probability got installed but not keras. I encountered the error stating

ERROR: Could not find a version that satisfies the requirement tf-keras==2.11.0 (from versions: 2.14.1, 2.15.0rc0, 2.15.0rc1, 2.15.0, 2.15.1rc0, 2.15.1, 2.16.0rc0, 2.16.0rc1, 2.16.0rc2, 2.16.0rc3, 2.16.0rc4, 2.16.0)
ERROR: No matching distribution found for tf-keras==2.11.0
WARNING: You are using pip version 22.0.4; however, version 24.0 is available.
You should consider upgrading via the '/home/pi/.pyenv/versions/3.10.4/bin/python3.10 -m pip install --upgrade pip' command.

**Comment by maddinkunze** [comment]
My bad, copy-paste-error. Please try with `tf-keras==2.14.1` and report back. If it works i will fix the requirements.txt together with updating the readme :)

**Comment by rahul8819** [comment]
Tried with keras 2.14.1, installed succesfully. But on running main.py produces a similar error message.

The following unhandled exception occured: No module named 'tensorflow'

Traceback (most recent call last):

File

"/home/pi/handcode/src/main.py ", line 440, in thread Convert import handwriting

File

"/home/pi/handcode/src/lib/hand writing/init.py", line 1, in

<module>

from. import gcode

File

"/home/pi/handcode/src/lib/hand

writing/gcode.py", line 3, in

<module>

from.rnn import rnn

File

"/home/pi/handcode/src/lib/hand writing/rnn.py", line 5, in

<module>

import tensorflow as tf ModuleNotFoundError: No module named 'tensorflow'

(<class 'ModuleNotFoundError'>, ModuleNotFoundError("No module named 'tensorflow'"), <traceback object at 0x7ffed178a080>)


![WhatsApp Image 2024-03-22 at 16 22 41](https://github.com/maddinkunze/handcode/assets/107311046/342b65fb-4262-49b2-908c-d313d41fbfa4)

**Comment by maddinkunze** [comment]
You have to reinstall all python libraries (tf, keras, ...) for python 3.10, i presume the libraries were previously installed for the other python3 version you had. Please check if the python version for pip is also python 3.10. You can check this using `pip -V` or `pip3 -V`. If it is 3.10 you can simply use `pip` or `pip3`, otherwise you can use `python -m pip` to get pip for the correct version of python, and you can use it to reinstall requirements.txt, so either `pip install -r requirements.txt` or `python -m pip install -r requirements.txt`

**Comment by rahul8819** [comment]
Sure, I'll give that a try and let you know how it goes.  (Which version of Keras should we utilize: 2.11.0 or 2.14.1?)

Additionally, I'm curious if it's possible to incorporate our custom handwriting font style. I've created an .otf file using a calligraphy template. Can we apply a similar process in this context?

**Comment by maddinkunze** [comment]
Use `tf-keras==2.14.1`.

Yes, you can use your own handwriting but you have to train the model with (very very many) handwriting strokes. It is relatively time consuming to get enough reliable training and testing data and to understand the training process, but i think i have linked something in the readme about this.

My program does not support fonts (your otf file is a font), it only supports trained handwriting which requires way more data than just one drawing per character, but feel free to test one of the 12 pretrained handwriting styles. If you want to use a custom font, you simply need to use a word processor (Microsoft Word, OpenOffice, LibreOffice, ...) and import your font into either the system or program context but i guess there are way better tutorials on how to import a custom font into your word processor of choice than i could give you.

**Comment by rahul8819** [comment]
I have reinstalled everything as specified and i encountered another error on running main.py


The following unhandled exception occured: module

'tensorflow' has no attribute

'compat'

Traceback (most recent call last):

File

"/home/pi/handcode/src/main.py ", line 440, in thread Convert import handwriting

File

"/home/pi/handcode/src/lib/hand writing/init_.py", line 1, in

<module>

from. import gcode

File

"/home/pi/handcode/src/lib/hand writing/gcode.py", line 3, in

<module>

from.rnn import rnn

File

"/home/pi/handcode/src/lib/hand writing/rnn.py", line 6, in

<module>

tf.compat.v1.disable_v2_beh

avior() AttributeError: module

'tensorflow' has no attribute

'compat'

(<class 'AttributeError'>,

AttributeError("module

'tensorflow' has no attribute

'compat'"), <traceback object at 0x7fff5d468d00>)


![WhatsApp Image 2024-03-23 at 13 47 57](https://github.com/maddinkunze/handcode/assets/107311046/c0197282-6c31-4ac3-b395-e2cfd3263e13)

**Comment by maddinkunze** [comment]
Try installing `pip install tf-estimator==2.11.0`, might be an issue with tf dependencies

**Comment by rahul8819** [comment]
Received this error:
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement tf-estimator==2.11.0 (from versions: none)
ERROR: No matching distribution found for tf-estimator==2.11.0

**Comment by maddinkunze** [comment]
Alright, im all out of ideas. You can try reinstalling everything.

So to uninstall everything

```
sudo apt-get clean
sudo apt-get autoremove --purge
sudo apt-get remove python3
sudo apt-get autoremove
```

Do the above mentioned steps as long as calling `python3` or `pip3` does not throw a not found error

and then reinstall everything
```
sudo apt-get install python3.10
cd path/to/handcode
sudo pip3 install -r requirements.txt
```

If the issue persists after that i have no clue, the steps mentioned above have been tested on a clean Ubuntu install.

In the future i will try to switch to tflite for more portability, snappier interactions and smaller build size, but until then you may have to troubleshoot your error yourselves. I may be able to help though, if a different error occurs.

**Comment by rahul8819** [comment]
I formatted my raspberry pi and installed everything as you specified. But sadly i am getting the same error message as "Tensorflow module not found".

![WhatsApp Image 2024-03-24 at 10 44 58](https://github.com/maddinkunze/handcode/assets/107311046/cb9426c4-83b9-44fd-be28-be001787f753)

**Comment by rahul8819** [comment]
Hi There is an update regarding the issue i was facing previously.
I used python 3.10.10
When i run main.py in VS Code the error regarding the tensorflow is now not showing and everything got loaded perfectly.

![WhatsApp Image 2024-03-24 at 13 16 33](https://github.com/maddinkunze/handcode/assets/107311046/23e3b095-7a4b-484c-8893-8e46c0de04a8)


But when i clicked "start" button after typing some texts it shows "saving settings"

![WhatsApp Image 2024-03-24 at 13 19 05](https://github.com/maddinkunze/handcode/assets/107311046/5e377c9b-a850-45c2-8f06-a6554d7ffc7c)


I will share the messages in the terminal:-
> On running the program:
(venv) pi@raspberrypi5:~/handcode $ /home/pi/handcode/venv/bin/python /home/pi/handcode/src/main.py
WARNING:tensorflow:From /home/pi/handcode/venv/lib/python3.10/site-packages/tensorflow/python/compat/v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term

new run with parameters:
{'attention_mixture_components': 10,
 'batch_size': 32,
 'batch_sizes': [32, 64, 64],
 'beta1_decay': 0.9,
 'beta1_decays': [0.9, 0.9, 0.9],
 'checkpoint_dir': '/home/pi/handcode/src/lib/handwriting/checkpoints',
 'early_stopping_steps': 1500,
 'enable_parameter_averaging': False,
 'grad_clip': 10,
 'keep_prob_scalar': 1.0,
 'learning_rate': 0.0001,
 'learning_rates': [0.0001, 5e-05, 2e-05],
 'log_dir': '/home/pi/handcode/src/lib/handwriting/logs',
 'log_interval': 20,
 'logging_level': 20,
 'loss_averaging_window': 100,
 'lstm_size': 400,
 'min_steps_to_checkpoint': 2000,
 'num_restarts': 2,
 'num_training_steps': 100000,
 'optimizer': 'rms',
 'output_mixture_components': 20,
 'output_units': 121,
 'patiences': [1500, 1000, 500],
 'prediction_dir': '/home/pi/handcode/src/lib/handwriting/predictions',
 'reader': None,
 'regularization_constant': 0.0,
 'restart_idx': 0,
 'validation_batch_size': 32,
 'warm_start_init_step': 17900}
WARNING:tensorflow:From /home/pi/handcode/src/lib/handwriting/rnn.py:132: dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use keras.layers.RNN(cell), which is equivalent to this API
From /home/pi/handcode/src/lib/handwriting/rnn.py:132: dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use keras.layers.RNN(cell), which is equivalent to this API
/home/pi/handcode/src/lib/handwriting/rnn_cell.py:81: UserWarning: tf.nn.rnn_cell.LSTMCell is deprecated and will be removed in a future version. This class is equivalent as tf.keras.layers.LSTMCell, and will be replaced by that in Tensorflow 2.0.
  cell1 = tf.compat.v1.nn.rnn_cell.LSTMCell(self.lstm_size)
WARNING:tensorflow:From /home/pi/handcode/venv/lib/python3.10/site-packages/keras/layers/rnn/legacy_cells.py:1048: calling Zeros._init_ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
From /home/pi/handcode/venv/lib/python3.10/site-packages/keras/layers/rnn/legacy_cells.py:1048: calling Zeros._init_ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
/home/pi/handcode/src/lib/handwriting/rnn_cell.py:105: UserWarning: tf.nn.rnn_cell.LSTMCell is deprecated and will be removed in a future version. This class is equivalent as tf.keras.layers.LSTMCell, and will be replaced by that in Tensorflow 2.0.
  cell2 = tf.compat.v1.nn.rnn_cell.LSTMCell(self.lstm_size)
/home/pi/handcode/src/lib/handwriting/rnn_cell.py:110: UserWarning: tf.nn.rnn_cell.LSTMCell is deprecated and will be removed in a future version. This class is equivalent as tf.keras.layers.LSTMCell, and will be replaced by that in Tensorflow 2.0.
  cell3 = tf.compat.v1.nn.rnn_cell.LSTMCell(self.lstm_size)
WARNING:tensorflow:From /home/pi/handcode/venv/lib/python3.10/site-packages/tensorflow/python/training/rmsprop.py:188: calling Ones._init_ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
From /home/pi/handcode/venv/lib/python3.10/site-packages/tensorflow/python/training/rmsprop.py:188: calling Ones._init_ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
all parameters:
[('Variable:0', []),
 ('Variable_1:0', []),
 ('Variable_2:0', []),
 ('rnn/LSTMAttentionCell/lstm_cell/kernel:0', [476, 1600]),
 ('rnn/LSTMAttentionCell/lstm_cell/bias:0', [1600]),
 ('rnn/LSTMAttentionCell/attention/weights:0', [476, 30]),
 ('rnn/LSTMAttentionCell/attention/biases:0', [30]),
 ('rnn/LSTMAttentionCell/lstm_cell_1/kernel:0', [876, 1600]),
 ('rnn/LSTMAttentionCell/lstm_cell_1/bias:0', [1600]),
 ('rnn/LSTMAttentionCell/lstm_cell_2/kernel:0', [876, 1600]),
 ('rnn/LSTMAttentionCell/lstm_cell_2/bias:0', [1600]),
 ('rnn/gmm/weights:0', [400, 121]),
 ('rnn/gmm/biases:0', [121]),
 ('rnn/LSTMAttentionCell/lstm_cell/kernel/RMSProp:0', [476, 1600]),
 ('rnn/LSTMAttentionCell/lstm_cell/kernel/RMSProp_1:0', [476, 1600]),
 ('rnn/LSTMAttentionCell/lstm_cell/bias/RMSProp:0', [1600]),
 ('rnn/LSTMAttentionCell/lstm_cell/bias/RMSProp_1:0', [1600]),
 ('rnn/LSTMAttentionCell/attention/weights/RMSProp:0', [476, 30]),
 ('rnn/LSTMAttentionCell/attention/weights/RMSProp_1:0', [476, 30]),
 ('rnn/LSTMAttentionCell/attention/biases/RMSProp:0', [30]),
 ('rnn/LSTMAttentionCell/attention/biases/RMSProp_1:0', [30]),
 ('rnn/LSTMAttentionCell/lstm_cell_1/kernel/RMSProp:0', [876, 1600]),
 ('rnn/LSTMAttentionCell/lstm_cell_1/kernel/RMSProp_1:0', [876, 1600]),
 ('rnn/LSTMAttentionCell/lstm_cell_1/bias/RMSProp:0', [1600]),
 ('rnn/LSTMAttentionCell/lstm_cell_1/bias/RMSProp_1:0', [1600]),
 ('rnn/LSTMAttentionCell/lstm_cell_2/kernel/RMSProp:0', [876, 1600]),
 ('rnn/LSTMAttentionCell/lstm_cell_2/kernel/RMSProp_1:0', [876, 1600]),
 ('rnn/LSTMAttentionCell/lstm_cell_2/bias/RMSProp:0', [1600]),
 ('rnn/LSTMAttentionCell/lstm_cell_2/bias/RMSProp_1:0', [1600]),
 ('rnn/gmm/weights/RMSProp:0', [400, 121]),
 ('rnn/gmm/weights/RMSProp_1:0', [400, 121]),
 ('rnn/gmm/biases/RMSProp:0', [121]),
 ('rnn/gmm/biases/RMSProp_1:0', [121])]
trainable parameters:
[('rnn/LSTMAttentionCell/lstm_cell/kernel:0', [476, 1600]),
 ('rnn/LSTMAttentionCell/lstm_cell/bias:0', [1600]),
 ('rnn/LSTMAttentionCell/attention/weights:0', [476, 30]),
 ('rnn/LSTMAttentionCell/attention/biases:0', [30]),
 ('rnn/LSTMAttentionCell/lstm_cell_1/kernel:0', [876, 1600]),
 ('rnn/LSTMAttentionCell/lstm_cell_1/bias:0', [1600]),
 ('rnn/LSTMAttentionCell/lstm_cell_2/kernel:0', [876, 1600]),
 ('rnn/LSTMAttentionCell/lstm_cell_2/bias:0', [1600]),
 ('rnn/gmm/weights:0', [400, 121]),
 ('rnn/gmm/biases:0', [121])]
trainable parameter count:
3632431
built graph
restoring model parameters from /home/pi/handcode/src/lib/handwriting/checkpoints/model-17900
INFO:tensorflow:Restoring parameters from /home/pi/handcode/src/lib/handwriting/checkpoints/model-17900
Restoring parameters from /home/pi/handcode/src/lib/handwriting/checkpoints/model-17900
2024-03-24 13:20:48.735055: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:357] MLIR V1 optimization pass is not enabled

>On clicking the start buton:
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/pi/.pyenv/versions/3.10.4/lib/python3.10/tkinter/_init.py", line 1921, in __call_
    return self.func(*args)
  File "/home/pi/handcode/src/main.py", line 429, in startConvert
    saveSettingsToFile()
  File "/home/pi/handcode/src/main.py", line 735, in saveSettingsToFile
    file = open(_pathSettings, "w")
FileNotFoundError: [Errno 2] No such file or directory: 'data/settings.json'



Also the program runs only in VS code. When i run the program directly from terminal, its shows the previous tensorflow module not found error.

**Comment by rahul8819** [comment]
Thank you so much for helping me It works perfectly now !!!!!!!!!

(For me it worked by using python 3.10.10)

**Comment by maddinkunze** [comment]
Happy to help, have tun with HandCode 👍

**Comment by rahul8819** [comment]
Hi, Need a quick help
When attempting to run the generated G-code file through Universal G-code Sender, the servo motor controlling the pen does not move, but both X and Y axes moves perfectly

**Comment by maddinkunze** [comment]
Hi, im really sorry for the delay, i will look into this an come back to you within the next week.

In the meantime, please have a look into the generated GCode/NC file. It should contain commands like `G0 Z0.000` (travel->write moves) and `G0 Z5.000` (write->travel moves). HandCode was built for machines supporting 3 freely controllable axis (i.e. cnc routers, 3d printers). You state that you have a binary Z-Axis (pen down/pen up).

To fix your issue you can probably replace all `G0 Z0` commands with your pen down command (e.g. `M3`) and all `G0 Z5` with your pen up commands (e.g. `M5`).

The actual Z value are what you entered in the HandCode UI as Z heights for write and travel moves. Furthermore, it could be `G1`, `G01` or `G00` instead of `G0`. Also, the actual commands replacing the current z moves are probably not `M3` and `M5`, but they should be documented somewhere with the GCode interpreter you are using.

If it is still not working, please open a new issue and close this again as those are unrelated topics.

**Comment by rahul8819** [comment]
Sure i will check it out.

**Comment by maddinkunze** [comment]
A new issue for supporting servo based (+ motor and laser based) machines has been opened: #2
