### ISSUE TITLE
Servo motor (Z axis) control

### ISSUE THREAD

**Issue by rahul8819** [maddinkunze/handcode#2]
Hello, I attempted to modify the `commands.py` file according to your suggestion, incorporating the new code provided below:

```
 def gcode(pendraw=0, pentravel=5, penpause=50, feeddraw=1000, feedtravel=1000, servo_up=250, servo_down=90):
    return {
        "draw": {
            "start": None,
            "move": f"G1 X{{x:f}} Y{{y:f}} Z{pendraw} F{feeddraw}\n",
            "end": None,
        },
        "travel": {
            "start": None,
            "move": f"G0 X{{x:f}} Y{{y:f}} Z{pentravel} F{feedtravel}\n",
            "end": None
        },
        "page": {
            "start": None,
            "next": f"G0 Z{penpause} F{feedtravel}\nM03 s{servo_up}\n",
            "end": f"G0 Z{penpause} F{feedtravel}\nM03 s{servo_down}\n"
        }
    }


```
I employed the "M03 s250" command to raise the servo and "M03 s90" to lower it. This method proved effective when tested in the command window of the G-code sender. Also, I modified `gcode.py` by providing the same command.

However, despite my efforts, it seems that the changes made to the file did not affect the control of the z-axis.

**Comment by maddinkunze** [comment]
Could you please provide some resources on what setup you are using?
Especially important is the program you are feeding the generated GCode file into.
If you followed a tutorial to build your handwriting robot you can link that as well.

**Comment by rahul8819** [comment]
I built a CNC sketching device following a tutorial found here:  [https://www.youtube.com/watch?v=5qAwCg7XPZw]

Now, I'm looking to enhance the same setup into a handwriting robot by integrating a Raspberry Pi 5 instead of a computer. I currently rely on Universal G-code Sender to facilitate the transfer of G-code files from Handcode to the machine.

**Comment by maddinkunze** [comment]
Alright, after looking at the video, it seems there are two possible scenarios for the GCode commands you need to use:
```
G3 S{speedon} // on, where {speedon} is some number correlating to the wanted speed (i.e. motor speed when milling, laser power for laser engraving, servo angle pushing the pen down like in your case)
G3 S{speedoff} // off, where {speed} is some number correlating to an inactive tool (i.e. 0 for milling and laser engraving, some other servo angle pulling the pen up)
```
or (unlikely)
```
G3 S{speed} // on, where {speed} is some number correlating to the wanted speed (i.e. motor speed when milling, laser power for laser engraving, ...)
G5 // off, turns the motor/laser/... completely off
```

I've implemented a simple GCode generator for both cases in the `commands.py` file in the following commits: 0bd276e0ee0589c9ab792a912adf60c9db1eaa8c 095f241dfc81e50dc65c7f87cb963b0077321ea6

Please pull the changes in your repository using `git pull` (all changes made by you will be lost unless you commit them to your local repo) and the change line 444 in file `src/main.py` to `_pensettingsgen["gcode"] = handwriting.commands.gcode_laser`

After this, the you can values enter the Servo Angles in the UI for Z Pen Draw, Travel and Pause (page swap) respectively.

If it still does not work, please share a file returned by my tool on your machine.

**Comment by rahul8819** [comment]
Thank you for your time, it's now operating seamlessly.
